version: 2

jobs:
  build:
    working_directory: /go/src/github.com/LayerXcom/gram
    docker:
    - image: golang:1.10
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/...
    - run: dep ensure
    - run: go test -v -race ./...
    - run: go test -bench .
    - run: go build .
